name: tests

on:
  # Trigger the workflow on push or pull request on main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run cron job every month, https://crontab.guru/every-month
    - cron: '0 0 1 * *'

jobs:
  # This job tests that the CC works
  test-cc-and-jb-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # currently not testing on windows
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    # Setup
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Use the default CC
    - name: Check black style
      run: |
        black ./ --check
    # Run tests
    - name: Pytest tests
      run: |
        pytest
    